### ISSUE TITLE
纯小白想请教下 python运行error

### ISSUE THREAD

**Issue by lisha3** [264768502/qiandao#1]
Hello，不会python，研究了下才知道怎么弄，但是出现问题我就不懂了，求教，谢谢啦！

File "/Users/xxx/Downloads/kanzhun.py", line 122, in <module>
    k.getsignpoint()
  File "/Users/xxx/Downloads/kanzhun.py", line 109, in getsignpoint
    self.logger.logprint("Get Sign Point Success: {}".format(re_point.search(res.content).group(1)))
TypeError: cannot use a string pattern on a bytes-like object

**Comment by 264768502** [comment]
我猜你用的是Python3,所以报错了.随手写的没考虑2和3的兼容性,也没在README里注明,我的错.
以Python2来说,"Get Sign Point Success: {}"是str,也是byte,而re_point.search(res.content).group(1))返回的是str/byte. 所以类型匹配,可以正常字符串格式化.
以Python3来说,"Get Sign Point Success: {}"是str,不是byte,而re_point.search(res.content).group(1))返回的是byte. 类型不匹配,所以报错说TypeError

**Comment by lisha3** [comment]
非常感谢你的回复。所以说这个error不会影响效果吧？是不是只要运行一次就会每天自动签到？由于后来用了一个签到网站所以没有去验证。

**Comment by 264768502** [comment]
因为报异常了,所以只走到登录那一步,没走到签到
另外是需要每天运行一次才可以

**Comment by 264768502** [comment]
加了一点点保护,现在应该可以正常运行了

**Comment by lisha3** [comment]
谢谢哦，我去看看 ：）
